# yamllint disable rule:line-length
name: Platform Contract

"on":
  pull_request:
    paths:
      - goreecloud.platform.yaml
      - .github/workflows/platform-contract.yml
  push:
    branches:
      - main
    paths:
      - goreecloud.platform.yaml
      - .github/workflows/platform-contract.yml
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate:
    uses: GoreeCloud/GoreeCloud/.github/workflows/reusable-platform-manifest.yml@5bb49dd878b90f140c7af4be1f7b1af0fddbe93c
    with:
      manifest-path: goreecloud.platform.yaml
